apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: tiny-jammy
spec:
  order:
  - group:
    - id: tanzu-buildpacks/java-native-image-lite
  - group:
    - id: tanzu-buildpacks/java-lite
  - group:
    - id: tanzu-buildpacks/go-lite
  - group:
    - id: paketo-buildpacks/procfile
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  stack:
    kind: ClusterStack
    name: tiny-jammy
  tag: europe-west4-docker.pkg.dev/tap-sandbox-dev/tapv-proud-corgi/buildservice:tiny-jammy